flaskapp/models.py
from datetime import datetime
from flaskapp import db, login_manager
from flask import current_app
from flask_login import UserMixin

# class User(db.Model, UserMixin):

flaskapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
#login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'

from flaskapp.main.routes import main
# from flaskapp.users.routes import users
# from flaskapp.posts.routes import posts

from flaskapp.errors.handlers import errors

def create_app():
    app = Flask(__name__)
    #app.config from_object(Config)
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    app.config['SECRET_KEY']=''
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///flaskdb.db'

    app.register_blueprint(main)
    # app.register_blueprint(users)
    # app.register_blueprint(posts)
    
    app.register_blueprint(errors)

    return app

flaskapp/main/routes.py
from flask import render_template, request, Blueprint
from flaskapp import db
# from flaskapp.models import User
# from flaskapp.posts.forms import UserForm

main = Blueprint('main',__name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')

@main.route("/about")
def about():
    return render_template('about.html', title='about')

flaskapp/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>Hello world form about</h1>
{% endblock %}

flaskapp/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1>Hello world</h1>
{% endblock %}

flaskapp/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        {% if title %}
        <title>MyAppFlask - {{ title }}</title>
        {% else %}
            <title>MyAppFlask</title>
        {% endif%}
        <!-- <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static',filename='css/main.css') }}"> -->
    </head>
    <body>
                  
            <!-- <a href="{{ url_for('main.home') }}" class="nav-item nav-link">Home</a>
            <a href="{{ url_for('main.about') }}" class="nav-item nav-link">About</a> -->
            
            <!-- <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                {% else %}
                {% endif %}
            </div> -->
        
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        
        <!-- <script type="text/javascript" src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script> -->
    </body>
</html>